name: "Composite Action"
description: "Composite Action"
inputs:
  ENVIRONMENT:
    description: "GCPのENVIRONMENT"
    required: true

runs:
  using: "composite"
  steps:     # https://cloud.google.com/iam/docs/using-workload-identity-federation#generate-automatic
    # https://github.com/hashicorp/setup-terraform
    - uses: hashicorp/setup-terraform@v2

    - name: Terraform fmt
      shell: bash
       run: |
          pwd
      id: fmt
      run: terraform fmt -check -recursive
      continue-on-error: true

    - name: Terraform Init
      shell: bash
      id: init
      run: terraform init

    - name: Terraform Validate
      shell: bash
      id: validate
      run: terraform validate -no-color

    - name: Terraform Plan
      shell: bash
      id: plan
      run: terraform plan -no-color
      continue-on-error: true

    - name: Terraform Plan Status
      shell: bash
      if: steps.plan.outcome == 'failure'
      run: exit 1

    # main ブランチに push した場合にだけ terraform apply も実行される
    - name: Terraform Apply
      shell: bash
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: terraform apply -auto-approve -input=false
