name: terraform
  
# main ブランチへのPull Request と Merge をトリガーに指定
on:
  push:
    branches:
      - main
  pull_request:
    
# ジョブ / ステップ / アクションの定義
jobs:
  terraform-workflow:
    runs-on: ubuntu-latest
    # 作業ディレクトリの指定
    defaults:
      run:
        working-directory: ./dev
    permissions:
      id-token: write
      contents: read
      pull-requests: write
  
    # Workload Identity 連携
    steps:
      - uses: actions/checkout@v3
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: 'projects/603621274592/locations/global/workloadIdentityPools/mypool/providers/myprovider'
          service_account: 'tf-exec@myproject.iam.gserviceaccount.com'

      - name: "call composite"
        uses: ./.github/actions
        with:
          WORKING_DIRECTORY: dev