name: terraform
  
# main ブランチへのPull Request と Merge をトリガーに指定
on:
  push:
    branches:
      - main
  pull_request:
  
# 作業ディレクトリの指定
defaults:
  run:
    working-directory: ./
  
# ジョブ / ステップ / アクションの定義
jobs:
  terraform-workflow:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      pull-requests: write
  
    # Workload Identity 連携
    steps:
      - name: "call composite"
        uses: ./.github/actions
        with:
          AWS_ENVIRONMENT: aaa